# Decrypt the file containing the key
steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - kms
  - decrypt
  - --ciphertext-file=id_rsa.enc
  - --plaintext-file=/root/.ssh/id_rsa
  - --location=global
  - --keyring=my-keyring
  - --key=github-key
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Set up git with key and domain.
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    chmod 600 /root/.ssh/id_rsa
    cat <<EOF >/root/.ssh/config
    Hostname github.com
    IdentityFile /root/.ssh/id_rsa
    EOF
    mv known_hosts /root/.ssh/known_hosts
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Use git clone.
- name: 'gcr.io/cloud-builders/git'
  args:
  - clone
  - --single-branch 
  - -b 
  - $BRANCH_NAME
  - git@github.com:SwiftIQ/$REPO_NAME.git
  volumes:
  - name: 'ssh'
    path: /root/.ssh
- name: 'gcr.io/cloud-builders/mvn'
  args: ['install']
  dir: $REPO_NAME
  volumes:
  - name: 'ssh'
    path: /root/.ssh
#steps:
#- name: gcr.io/cloud-builders/gsutil
#  args: ['cp', '$REPO_NAME/ear/target/ear-$REVISION_ID.ear', 'gs://dev3-siq/artifacts/$BRANCH_NAME/ear-$REVISION_ID.ear']
